[package]
name = "fallendust"
version = "0.1.0"
edition = "2024"

[dependencies]
ferrousgl = "0.0.11"
glam = "0.30.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.10.0"
gl = "0.14.0"
noise = "0.9.0"